### ISSUE TITLE
transactionId has numerical error

### ISSUE THREAD

**Issue by keydepth** [r3850355/line-pay-v3#2]
Response transactionId is 19 digit.
JavaScript(JSON) could not handle 19 digit.
So, transactionId has numerical error.
json-bigint can handle 19 digit.

**Comment by keydepth** [comment]
Updated 
Commit 45420db40f4f86b9b5c300ab8fb12ec0a1c0d2cb

**Comment by keydepth** [comment]
Thank you for merge.

**Comment by nayrlester** [comment]
got an issue in the update.
error calling __jsonbig
it shoud be this.__jsonbig
